### ISSUE TITLE
Mixed code indentation

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [bluespec/Piccolo#11]
This is a minor issue.

For SSITH, I may extend the source code of Piccolo (and Flute). During these early phases, I am reading and understanding the source code. I noticed some mixed (tab, spaces) or non-correct indentation that reduces the code readability. I can easily fix it on my side as I proceed with my feature integration, but it would be great to have it fixed on the baseline.

Thank you!

**Comment by GiuseppeDiGuglielmo** [comment]
I can also fork the repo, fix the indentation issues, and make a pull request. Let me know what you may prefer.

**Comment by rsnikhil** [comment]
Pull requests would be best.
