### ISSUE TITLE
Suspicion of bug in the deburster

### ISSUE THREAD

**Issue by gameboo** [bluespec/Piccolo#16]
Simply from reading the code at https://github.com/bluespec/Piccolo/blob/master/src_Testbench/Fabrics/AXI4/AXI4_Deburster.bsv#L174 (understand "I have not tested what I am about to claim in any way"), it looks to me like a single write request may receive many write responses. Maybe it does not really matter if in practice those responses are ignored, but I presume that this is in general undesirable?
Or am I simply missing something?

**Comment by rsnikhil** [comment]
Yes, you are quite right in your analysis.

It _does_ matter in practice: many clients monitor write-responses in case of errors in the fabric or slave, or for certainty that a write has reached memory, and giving the wrong number of responses would throw them out of sync.

I have pushed a fix for the problem.

Thanks!
